### ISSUE TITLE
index page > validation: js toggle doesn’t work

### ISSUE THREAD

**Issue by furter** [hybrid-publishing-lab/hybrid-publishing-research#15]
I tried to implement a js toggle button but it seems to conflict with angular. What would be the angular way of doing it?

https://github.com/consortium/hybrid-publishing-research/blob/9a005972cefcb8455372b0ec54e3ef944341be65/js/consortium-viewer.js#L61

**Comment by dreh23** [comment]
This issue was moved to consortium/hybrid-publishing-research#15
