### ISSUE TITLE
Publication summary content

### ISSUE THREAD

**Issue by mrchristian** [hybrid-publishing-lab/hybrid-publishing-research#25]
Hi,

We need to review what is going in the summary views on the index page. Currently its not enough.

Suggestions:
Short title - this is a convention that is allowed, so maybe we intro it into the metadata
Authors - two and indication or more?
Date
Permanent publication Identifier - not a revision identifier
Validation - indication of what is being validated against. The reason for the importance of the validation to to promote trust in what we are doing. Trust and reassurance is key to adoption and the success of publishing systems.

We should review these issues together.

S

**Comment by dreh23** [comment]
This issue was moved to consortium/hybrid-publishing-research#25
