### ISSUE TITLE
Metadata log needed

### ISSUE THREAD

**Issue by furter** [hybrid-publishing-lab/hybrid-publishing-research#28]
<meta charset="utf-8" /> 
    <meta name="generator" content="a-machine" /> 
    <meta name="keywords" content="a-machine, hybrid publishing consortium, template"/> 
    <meta name="description" content="About your document: description"/> 
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/> 
    <meta name="viewport" content="width=device-width, initial-scale=1"/> 
    
    <meta name="DC.title" content="My document title"/> 
    <meta name="DC.contributor" content="the author: a person, an organization, or a service. For each author make a new meta author"/> 
    <meta name="DC.creator" content="creator of this HTML document (not the author, just the person who generated the file)" /> 
    <meta name="DC.subject" content="keywords, key phrases, or classification codes, best using controlled vocabularies"> 
    <meta name="DC.description.abstract" content="About the document: description abstract"/> 
    <meta name="DC.date" content=""/> 
    <meta name="DC.type" content="The nature or genre of the report, research paper, article, essay, etc."/> 
    <meta name="DC.format" content="text/html"/> 
    <meta name="DC.language" content="eng"/> 
    <meta name="DC.identifier.URL" content="http://consortium.io"/> 
    <meta name="DC.rights" content="http://www.consortium.io/copyright"/> 
    <meta name="DC.identifier" content="ISBN, ISSN etc"/> 
    <meta name="DC.publisher" content="Hybrid Publishing Consortium. Entity responsible for making the document available"/> 
    <meta name="DC.bibliographicCitation" content="use a Chicago Manual of Style citation"/> 
    <link rel="SCHEMA.DC" href="http://purl.org/dc/elements/1.1/"/>

**Comment by dreh23** [comment]
This issue was moved to consortium/hybrid-publishing-research#28
