### ISSUE TITLE
Add DOI from Zenodo to doc where appropriate

### ISSUE THREAD

**Issue by mrchristian** [hybrid-publishing-lab/hybrid-publishing-research#30]
eg

https://zenodo.org/record/18166?ln=en#.VWt3QNOqqko

[![DOI](https://zenodo.org/badge/doi/10.5281/zenodo.18166.svg)](http://dx.doi.org/10.5281/zenodo.18166)
reStructedText

.. image:: https://zenodo.org/badge/doi/10.5281/zenodo.18166.svg   :target: http://dx.doi.org/10.5281/zenodo.18166
HTML

<a href="http://dx.doi.org/10.5281/zenodo.18166"><img src="https://zenodo.org/badge/doi/10.5281/zenodo.18166.svg" alt="10.5281/zenodo.18166"></a>
Image URL

https://zenodo.org/badge/doi/10.5281/zenodo.18166.svg
DOI URL

http://dx.doi.org/10.5281/zenodo.18166

**Comment by dreh23** [comment]
This issue was moved to consortium/hybrid-publishing-research#30
