### ISSUE TITLE
Metadata feed output

### ISSUE THREAD

**Issue by mrchristian** [hybrid-publishing-lab/hybrid-publishing-research#33]
We need a metadata feed output for other repositories to pickup on on publications. I'll look at what the format should be.

**Comment by dreh23** [comment]
What do you exactly mean? An rss feed or a json file? This json file already exists.

**Comment by mrchristian** [comment]
Hi J,

This is what I mean.

QUOTE

The OPDS Catalog is a syndication format for electronic publications based on Atom & HTTP. Catalogs enable the discovery, distribution & acquisition of publications. Catalogs use existing or emergent open standards, with a priority on simplicity. See http://code.google.com/p/openpub/

S

**Comment by dreh23** [comment]
The gitbook people tried to tackle some of this:

https://github.com/GitbookIO/opds-builder
https://github.com/GitbookIO/onix-builder

**Comment by dreh23** [comment]
This issue was moved to consortium/hybrid-publishing-research#33
