### ISSUE TITLE
Headers and footers in CSS print/PDF view

### ISSUE THREAD

**Issue by mrchristian** [hybrid-publishing-lab/hybrid-publishing-research#46]
Hi L,

Can we have these in Headers and footers in CSS print/PDF view, its just that its very handy to have the id of the doc and name etc.

S

**Comment by furter** [comment]
Do you mean like running title? This depends on the browser and the user’s settings.
If you mean just at the very beginning and end of the document: for the moment it is only when they are visible on the page and you click on print that they are printed.
But needs to be properly fixed!

**Comment by mrchristian** [comment]
I'm meaning a per page header and footer, so you know what your reading and if you have loose leaves, if one is on its own, you know where its from.

S

**Comment by dreh23** [comment]
This issue was moved to consortium/hybrid-publishing-research#46
