### ISSUE TITLE
Layout errors: Lines don't meet properly 

### ISSUE THREAD

**Issue by dreh23** [hybrid-publishing-lab/hybrid-publishing-research#51]
![wierdness](https://cloud.githubusercontent.com/assets/2920258/8283412/88d5f726-18f7-11e5-94e7-82eb91251c7b.png)

Chrome Linux Version 43.0.2357.125 (64-bit)
Firefox Linux 38

**Comment by dreh23** [comment]
funny enough on the server it looks much better, than on local development.

**Comment by furter** [comment]
Yeah it’s weird, on my computer(s) and browser(s) it doesn’t do that…
grrr

**Comment by dreh23** [comment]
Before you dive into it I will upgrade all frontend libraries and redo the js pipeline. Including the jqeury color bug.
Maybe some problems will go away.

**Comment by dreh23** [comment]
Libraries are now up-to-date. CSS is still acting a bit up. (I would love to integrate tests with phantomjs in future.)

**Comment by dreh23** [comment]
This issue was moved to consortium/hybrid-publishing-research#51
